export const productsData = [
     {
          id:1,
          img:'https://i.ibb.co/mTfd80j/p1.png'
     },
     {
          id:4,
          img:'https://i.ibb.co/h8D6rQr/p4.png'
     },
     {
          id:3,
          img:'https://i.ibb.co/HqC87G3/p3.png'
     },
     {
          id:2,
          img:'https://i.ibb.co/2dXNG2Z/p2.png'
     },
     {
          id:5,
          img:'https://i.ibb.co/WVfYhnB/p5.png'
     },
     {
          id:6,
          img:'https://i.ibb.co/fkD32Sn/p6.png'
     },
     {
          id:7,
          img:'https://i.ibb.co/1Gj9834/p7.png'
     },
     {
          id:8,
          img:'https://i.ibb.co/rwZmwNm/p8.png'
     }
]